# Generated by Django 4.2.5 on 2023-09-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('spam', models.BooleanField()),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
