# Generated by Django 4.2.5 on 2023-09-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allrecords',
            name='createdAt',
            field=models.DateTimeField(),
        ),
    ]
