# Generated by Django 4.2.5 on 2023-09-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_allrecords_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allrecords',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
